### ISSUE TITLE
google-cloud-logging errors - uninitialized constant Google::Cloud::Logging::VERSION

### ISSUE THREAD

**Issue by remi** [GoogleCloudPlatform/google-cloud-ruby#1054]
google-cloud-logging 0.21.1

`Google::Cloud::Logging::VERSION` is passed as the value for `app_version` but it is not loaded by `"google/cloud/logging"`

https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/service.rb#L74

```ruby
irb(main):001:0> require "google/cloud/logging"
=> true
irb(main):002:0> logging = Google::Cloud::Logging.new
=> #<Google::Cloud::Logging::Project:0x007fe93cae35f8 @service=Google::Cloud::Logging::Service(...)>
irb(main):003:0> logging.sinks
NameError: uninitialized constant Google::Cloud::Logging::VERSION
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-logging-0.21.1/lib/google/cloud/logging/service.rb:74:in `sinks'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-logging-0.21.1/lib/google/cloud/logging/service.rb:158:in `block in list_sinks'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-logging-0.21.1/lib/google/cloud/logging/service.rb:279:in `execute'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-logging-0.21.1/lib/google/cloud/logging/service.rb:157:in `list_sinks'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-logging-0.21.1/lib/google/cloud/logging/project.rb:498:in `sinks'
	from (irb):5
	from /Users/remily/.rbenv/versions/2.3.1/bin/irb:11:in `<top (required)>'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
	from /Users/remily/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
	from /Users/remily/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
	from /Users/remily/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by blowmage** [comment]
I've reproduced this by loading the gem without use of a Gemfile and Bundler. Every other service requires the version file, but Logging does not. The reason we haven't seen this previously is because Bundler will load the gemspec, which also loads the version file.

**Comment by blowmage** [comment]
Stackdriver Logging 0.21.2 is released with this fix. Thanks for being so diligent in examining these gems @remi!

https://github.com/GoogleCloudPlatform/google-cloud-ruby/releases/tag/google-cloud-logging%2Fv0.21.2
https://rubygems.org/gems/google-cloud-logging/versions/0.21.2
