### ISSUE TITLE
Speech doctest fails when run in a certain order

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#1163]
We've seen two build failures ([293](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-ruby/293), [294](https://circleci.com/gh/GoogleCloudPlatform/google-cloud-ruby/294)) when the doctest for `google-cloud-speech.rb:105` is the first test to be run.

```
***********************************
*** google-cloud-speech doctest ***
***********************************

bundle exec rake doctest
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
Files:           8
Modules:         3 (    2 undocumented)
Classes:         7 (    0 undocumented)
Constants:       1 (    1 undocumented)
Attributes:      7 (    0 undocumented)
Methods:        27 (    0 undocumented)
 93.33% documented
bundle exec yard config -a autoload_plugins yard-doctest
bundle exec yard doctest
Run options: --seed 10805

# Running:

E...........................................

Finished in 5.039354s, 8.7313 runs/s, 5.5563 assertions/s.

  1) Error:
Google::Cloud.speech#test_0001_:
RuntimeError: This code example is not yet mocked
    /home/ubuntu/google-cloud-ruby/google-cloud-speech/support/doctest_helper.rb:69:in `new'
    /home/ubuntu/google-cloud-ruby/google-cloud-speech/lib/google-cloud-speech.rb:105:in `speech'
    /opt/circleci/.rvm/gems/ruby-2.2.5/gems/yard-doctest-0.1.8/lib/yard/doctest/example.rb:77:in `context'
    /home/ubuntu/google-cloud-ruby/google-cloud-speech/lib/google-cloud-speech.rb:102
    /opt/circleci/.rvm/gems/ruby-2.2.5/gems/yard-doctest-0.1.8/lib/yard/doctest/example.rb:56:in `eval'
    /opt/circleci/.rvm/gems/ruby-2.2.5/gems/yard-doctest-0.1.8/lib/yard/doctest/example.rb:56:in `evaluate_example'
    /opt/circleci/.rvm/gems/ruby-2.2.5/gems/yard-doctest-0.1.8/lib/yard/doctest/example.rb:43:in `block (4 levels) in generate'
    /opt/circleci/.rvm/gems/ruby-2.2.5/gems/yard-doctest-0.1.8/lib/yard/doctest/example.rb:40:in `each'
    /opt/circleci/.rvm/gems/ruby-2.2.5/gems/yard-doctest-0.1.8/lib/yard/doctest/example.rb:40:in `block (3 levels) in generate'

44 runs, 28 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by blowmage** [comment]
The doctest helper has configuration for `Google::Cloud#speech`, but not for `Google::Cloud.speech`
