### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by hamdibayhan** [GoogleCloudPlatform/google-cloud-ruby#1188]
after I read your documentation for cloud vision and implemented my project, I got following error:
> undefined method `new' for Google::Cloud::Vision:Module

Then I solved the problem with I changed 
`vision = Google::Cloud::Vision.new` 
and 
```
test = Google::Cloud.new
vision = test.vision
```
 So I think your documentation is wrong and needs correction.

**Comment by quartzmo** [comment]
@hamdibayhan Thank you for reporting this issue. Can you please provide your entire code example, and link to the specific documentation example? I cannot reproduce the error when I follow [the examples in the main guide](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.21.1/google/cloud/vision), for instance, although I do get it if I just omit the first line, `require "google/cloud/vision"`.

```ruby
irb(main):001:0> vision = Google::Cloud::Vision.new
NoMethodError: undefined method `new' for Google::Cloud::Vision:Module
	from (irb):1
	...
irb(main):002:0> require "google/cloud/vision"
=> true
irb(main):003:0> vision = Google::Cloud::Vision.new
=> #<Google::Cloud::Vision::Project:0x007f8ef2be2a48 @service=Google::Cloud::Vision::Service(xxxxx)>
```

**Comment by hamdibayhan** [comment]
Unfortunately although I add X, I get the following error:

```
irb(main):001:0> require "google/cloud/vision"
=> true
irb(main):002:0> vision = Google::Cloud::Vision.new
NoMethodError: undefined method `new' for Google::Cloud::Vision:Module
        from (irb):2
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console.rb:65:in `start'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/console_helper.rb:9:in `start'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
        from /Users/eng/keywords-ready-web-app/bin/rails:9:in `<top (required)>'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `block in load'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:287:in `load'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/commands/rails.rb:6:in `call'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/command_wrapper.rb:38:in `call'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:191:in `block in serve'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:161:in `fork'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:161:in `serve'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/eng/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

```

**Comment by blowmage** [comment]
What version of `google-cloud-vision` are you using? Some older versions did not have that constructor.

**Comment by hamdibayhan** [comment]
I am using
> gem 'google-cloud-vision', '~> 0.20.0'

**Comment by blowmage** [comment]
Okay, that makes more sense. The `Google::Cloud::Vision.new` constructor was added, along with an update to the documentation to use it, in 0.21.0. If you compare the [0.20.0 documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.20.0/google/cloud/vision) to the [0.21.0 documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud-vision/v0.21.0/google/cloud/vision) you will see the difference. The 0.20.0 documentation uses `gcloud.vision`, while the 0.21.0 documentation uses `Google::Cloud::Vision.new`.

**Comment by hamdibayhan** [comment]
I've realized now, my fault, thank you for your help.

**Comment by blowmage** [comment]
Not a problem! Thanks for using the Google Cloud libraries. Let us know if you have other questions.
