### ISSUE TITLE
[Video Intelligence] Google::Gax::RetryError: running sample snippet.

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1498]
Hi,

I'm working on samples which use the Video Intelligence API. I tried following a workflow from the [example snippet](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.29.0/google/cloud/videointelligence/v1beta1/videointelligenceserviceclient) and I receive a `Google::Gax::RetryError:` which uses project id `usable-auth-library`. Both are shown below. How should I set the project id? 

Error:
```
Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by 7:Google Cloud Video Intelligence API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/videointelligence.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/google-gax-0.8.2/lib/google/gax/api_callable.rb:349:in `rescue in block (2 levels) in retryable'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/google-gax-0.8.2/lib/google/gax/api_callable.rb:343:in `block (2 levels) in retryable'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/google-gax-0.8.2/lib/google/gax/api_callable.rb:342:in `loop'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/google-gax-0.8.2/lib/google/gax/api_callable.rb:342:in `block in retryable'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/google-gax-0.8.2/lib/google/gax/api_callable.rb:262:in `block in catch_errors'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/google-gax-0.8.2/lib/google/gax/api_callable.rb:224:in `block in create_api_call'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/google-gax-0.8.2/lib/google/gax/api_callable.rb:250:in `block in create_api_call'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/google-cloud-video_intelligence-0.20.0/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb:247:in `annotate_video'
	from (irb):8
	from /Users/franknatividad/.rbenv/versions/2.3.3/bin/irb:11:in `<top (required)>'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /Users/franknatividad/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
	from /Users/franknatividad/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
	from /Users/franknatividad/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
```

Snippet:
```
require "google/cloud/video_intelligence/v1beta1"

video_intelligence_service_client = Google::Cloud::VideoIntelligence::V1beta1::VideoIntelligenceServiceClient.new
input_uri = "gs://demomaker/tomatoes.mp4"
features = []

# Register a callback during the method call.
operation = video_intelligence_service_client.annotate_video(input_uri, features) do |op|
  raise op.results.message if op.error?
  op_results = op.results
  # Process the results.

  metadata = op.metadata
  # Process the metadata.
end
```

Gemfile.lock (Using Ruby 2.4.1)
```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.1)
      public_suffix (~> 2.0, >= 2.0.2)
    faraday (0.12.1)
      multipart-post (>= 1.2, < 3)
    google-cloud-video_intelligence (0.20.0)
      google-gax (~> 0.8.0)
    google-gax (0.8.2)
      google-protobuf (~> 3.2)
      googleapis-common-protos (~> 1.3.5)
      googleauth (~> 0.5.1)
      grpc (~> 1.0)
      rly (~> 0.2.3)
    google-protobuf (3.3.0)
    googleapis-common-protos (1.3.5)
      google-protobuf (~> 3.2)
      grpc (~> 1.0)
    googleauth (0.5.1)
      faraday (~> 0.9)
      jwt (~> 1.4)
      logging (~> 2.0)
      memoist (~> 0.12)
      multi_json (~> 1.11)
      os (~> 0.9)
      signet (~> 0.7)
    grpc (1.3.4)
      google-protobuf (~> 3.1)
      googleauth (~> 0.5.1)
    jwt (1.5.6)
    little-plugger (1.1.4)
    logging (2.2.2)
      little-plugger (~> 1.1)
      multi_json (~> 1.10)
    memoist (0.15.0)
    multi_json (1.12.1)
    multipart-post (2.0.0)
    os (0.9.6)
    public_suffix (2.0.5)
    rly (0.2.3)
    signet (0.7.3)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (~> 1.5)
      multi_json (~> 1.10)

PLATFORMS
  ruby

DEPENDENCIES
  google-cloud-video_intelligence

BUNDLED WITH
   1.14.6
```

**Comment by blowmage** [comment]
Hi @frankyn, have you enabled the Video Intelligence API on that project? The key part of the error message is the following:

> Google Cloud Video Intelligence API has not been used in project usable-auth-library before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/videointelligence.googleapis.com/overview?project=usable-auth-library then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

**Comment by frankyn** [comment]
I'm not sure how `usable-auth-library` was used. I set the GOOGLE_CLOUD_PROJECT id and I enabled the video intelligence API for my project `spec-test-ruby-samples`.  Is there a parameter to set the project id?

**Comment by blowmage** [comment]
It doesn't look like Video Intelligence has `project_id` as part of its API. So I assume it is using the project associated with your authentication. How are you authenticating?

Video Intelligence is a GAPIC-only gem, and doesn't offer the same API for authentication as used by other Google Cloud gems.

**Comment by frankyn** [comment]
@blowmage, I thought I had setup my environment correctly, but I didn't define GOOGLE_APPLICATION_CREDENTIALS with a service account. @remi provided me an example and I was able to get passed this error. 

Thank you!
