### ISSUE TITLE
Resource Manager create_project example returns error

### ISSUE THREAD

**Issue by hxiong388** [GoogleCloudPlatform/google-cloud-ruby#1511]
While trying the code example of `ResourceManager::Manager#create_project`:

```ruby
require "google/cloud/resource_manager"

resource_manager = Google::Cloud::ResourceManager.new
project = resource_manager.create_project "tokyo-rain-123"
```

It returns this error:

```sh
.../google-cloud-ruby/google-cloud-resource_manager/lib/google/cloud/resource_manager/service.rb:133:in `rescue in execute': badRequest: Request contains an invalid argument. (Google::Cloud::InvalidArgumentError)
	from /usr/local/google/home/hexiong/gem_workspace/google-cloud-ruby/google-cloud-resource_manager/lib/google/cloud/resource_manager/service.rb:131:in `execute'
	from /usr/local/google/home/hexiong/gem_workspace/google-cloud-ruby/google-cloud-resource_manager/lib/google/cloud/resource_manager/service.rb:80:in `create_project'
	from /usr/local/google/home/hexiong/gem_workspace/google-cloud-ruby/google-cloud-resource_manager/lib/google/cloud/resource_manager/manager.rb:186:in `create_project'
	from test.rb:4:in `<main>'
```

**Comment by hxiong388** [comment]
This seems to be only happening when I use `#create_project`. The other methods work fine as expected.

I tried to dig into the underlying apiary client, but I couldn't figure out which argument was causing the error.
