### ISSUE TITLE
Resource Manager policy example fails

### ISSUE THREAD

**Issue by arhamahmed** [GoogleCloudPlatform/google-cloud-ruby#1602]
Calling `policy` on a project I own fails.

Example:
```ruby
require "google/cloud/resource_manager"

resource_manager = Google::Cloud::ResourceManager.new
project = resource_manager.project my_project_id

policy = project.policy # fails
```

The error:
```
Google::Cloud::InvalidArgumentError: badRequest: Request contains an invalid argument.
	from /usr/local/google/home/arhamahmed/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-resource_manager-0.25.0/lib/google/cloud/resource_manager/service.rb:133:in `rescue in execute'
	from /usr/local/google/home/arhamahmed/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-resource_manager-0.25.0/lib/google/cloud/resource_manager/service.rb:131:in `execute'
	from /usr/local/google/home/arhamahmed/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-resource_manager-0.25.0/lib/google/cloud/resource_manager/service.rb:103:in `get_policy'
	from /usr/local/google/home/arhamahmed/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google-cloud-resource_manager-0.25.0/lib/google/cloud/resource_manager/project.rb:363:in `policy'
	from (irb):7
	from /usr/local/google/home/arhamahmed/.rbenv/versions/2.3.1/bin/irb:11:in `<main>'
```

**Comment by quartzmo** [comment]
@arhamahmed Thanks for finding and reporting this error! We will attempt to reproduce and fix if needed. Appreciate the help!
