### ISSUE TITLE
Errors not being reported

### ISSUE THREAD

**Issue by rushilagr** [GoogleCloudPlatform/google-cloud-ruby#1679]
I have deployed a simple ruby web app (using Rack and Puma) on Google Container Engine and Im unable to enable Stackdriver error reporting. Although logging works perfectly

Since the gem states that it takes care of all configuration, I have simply installed and required the file at the top of my rack server file.

For my Google Cloud project, StackDriver error reporting is generally correctly configured since it shows me errors for other containers on the same ContainerEngine deployment.

For testing whether the error reporting works, I have setup an endpoint which triggers a Ruby StandardError and returns an HTTP 500.

The Stackdriver logs clearly show an error being reported but nothing appears on the Stackdriver error console.

Using gem version 0.8

**Comment by hxiong388** [comment]
Hi @rushilagr. Thanks for reporting the issue. A common pitfall for error reporting is that the [Cloud Error Reporting API](https://console.cloud.google.com/apis/api/clouderrorreporting.googleapis.com/overview) isn't enabled by default. Please make sure it is enable on your GCP project.

Also, I noticed you stated "Since the gem states that it takes care of all configuration, I have simply installed and required the file at the top of my rack server file." This is only true if you're using a Ruby on Rails application and include the Railtie class/file. For other rack-based applications, manually include the middleware is required. For example:

```ruby
require "stackdriver"

# Manually inject Error Reporting middleware into the rack stack
use Google::Cloud::ErrorReporting::Middleware
```

Please let us know if you're still having trouble with it.

**Comment by rushilagr** [comment]
The error reporting API was not enabled. The documentation around it is a bit confusing.

But even after enabling, It's not working.

Here is the error trace from server logs:
```
2017-08-23T14:43:44.614948258Z Puma starting in single mode...
2017-08-23T14:43:44.614992379Z * Version 3.10.0 (ruby 2.3.1-p112), codename: Russell's Teapot
2017-08-23T14:43:44.614996544Z * Min threads: 0, max threads: 16
2017-08-23T14:43:44.614999006Z * Environment: deployment
2017-08-23T14:43:44.615093217Z * Listening on tcp://0.0.0.0:9292
2017-08-23T14:43:44.615308706Z Use Ctrl-C to stop
2017-08-23T14:43:54.677106836Z 2017-08-23 14:43:54 +0000: Rack app error handling request { GET /admin/error }
2017-08-23T14:43:54.677141231Z #<StandardError: StandardError>
2017-08-23T14:43:54.677145246Z /usr/src/app/routes/admin.rb:45:in `block (3 levels) in <class:Server>'
2017-08-23T14:43:54.677148231Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:896:in `if_match'
2017-08-23T14:43:54.677151176Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:492:in `is'
2017-08-23T14:43:54.677153703Z /usr/src/app/routes/admin.rb:44:in `block (2 levels) in <class:Server>'
2017-08-23T14:43:54.677156287Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:827:in `always'
2017-08-23T14:43:54.677158643Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:818:in `_verb'
2017-08-23T14:43:54.677161112Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:416:in `get'
2017-08-23T14:43:54.677163433Z /usr/src/app/routes/admin.rb:42:in `block in <class:Server>'
2017-08-23T14:43:54.677166404Z /usr/local/bundle/gems/roda-2.29.0/lib/roda/plugins/multi_route.rb:213:in `instance_exec'
2017-08-23T14:43:54.677168847Z /usr/local/bundle/gems/roda-2.29.0/lib/roda/plugins/multi_route.rb:213:in `route'
2017-08-23T14:43:54.677171229Z /usr/src/app/server.rb:27:in `block (2 levels) in <class:Server>'
2017-08-23T14:43:54.677173636Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:896:in `if_match'
2017-08-23T14:43:54.677175947Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:534:in `on'
2017-08-23T14:43:54.677178099Z /usr/src/app/server.rb:26:in `block in <class:Server>'
2017-08-23T14:43:54.677180499Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:279:in `instance_exec'
2017-08-23T14:43:54.677183009Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:279:in `block in call'
2017-08-23T14:43:54.677185375Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:277:in `catch'
2017-08-23T14:43:54.677187613Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:277:in `call'
2017-08-23T14:43:54.677189922Z /usr/local/bundle/gems/roda-2.29.0/lib/roda/plugins/status_handler.rb:46:in `call'
2017-08-23T14:43:54.677192197Z /usr/local/bundle/gems/roda-2.29.0/lib/roda.rb:246:in `block in build_rack_app'
2017-08-23T14:43:54.677194703Z /usr/local/bundle/gems/google-cloud-error_reporting-0.26.1/lib/google/cloud/error_reporting/middleware.rb:75:in `call'
2017-08-23T14:43:54.677196989Z /usr/local/bundle/gems/rack-2.0.3/lib/rack/tempfile_reaper.rb:15:in `call'
2017-08-23T14:43:54.677199279Z /usr/local/bundle/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
2017-08-23T14:43:54.677211652Z /usr/local/bundle/gems/rack-2.0.3/lib/rack/chunked.rb:54:in `call'
2017-08-23T14:43:54.677214292Z /usr/local/bundle/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
2017-08-23T14:43:54.677216562Z /usr/local/bundle/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
2017-08-23T14:43:54.677218943Z /usr/local/bundle/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
2017-08-23T14:43:54.677221291Z /usr/local/bundle/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
2017-08-23T14:43:54.677223789Z /usr/local/bundle/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
2017-08-23T14:43:54.677226073Z /usr/local/bundle/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

My config.ru

```
require "./server.rb"
require 'stackdriver'
use Google::Cloud::ErrorReporting::Middleware

run Server.freeze.app
```

I am using another service, Sentry, in quite a similar fashion. Just adding the Middleware in the config.ru file, and thats working just fine.

Might be an issue with configuration.
The code is running on a kubernetes pod on GKE.

**Comment by rushilagr** [comment]
Another question,

What is the difference between Stackdriver Logging API (https://console.cloud.google.com/apis/api/logging.googleapis.com/overview?project=...)
and 
Stack Driver Logging Dashboard(https://console.cloud.google.com/logs/viewer?project=...)

Does the Stackdriver Logging API simply monitor the traffic on that particular API?

Thanks

**Comment by hxiong388** [comment]
@rushilagr Thanks for checking. I will test the `roda` gem with `google-cloud-error_reporting` to see if I can reproduce the issue.

> What is the difference between Stackdriver Logging API Dashboard (https://console.cloud.google.com/apis/api/logging.googleapis.com/overview?project=...)
> and
> the regular Stack Driver Logging Dashboard(https://console.cloud.google.com/logs/viewer?project=...)
> Does the Stackdriver Logging API dashboard simply monitor the traffic on that particular API?

You're correct. The Stackdriver Logging API Dashboard, and other API dashboards alike, just monitors the API usage.

**Comment by rushilagr** [comment]
Thanks for the quick reply Heng.

Roda is a simple wrapper on top on rack. And it is production tested, so it
would be very very unlikely that there is exists a problem specific to it.

Are there any other things I might be missing? Is there a checklist that I
can go through or some other details I can provide you?

**Comment by hxiong388** [comment]
Hi @rushilagr. I actually got Roda to work with the Stackdriver Error Reporting gem by using the Hello World app on Roda's home page. However, I further enabled Roda's built-in error handling mechanism to test if it interferes with Stackdriver Error Reporting:
```ruby
plugin :error_handler do |e|
  "Oh No!"
end
```
And sure enough, Roda's built-in error handling mechanism intercepts the raised exception and stops it from propagating up the Rack stack. Do you have such error handling mechanism enabled in your application by any chance? If so, you may need to explicitly report the exception to Stackdriver like so:
```ruby
plugin :error_handler do |e|
  Google::Cloud::ErrorReporting.report e
  "Oh No!"
end
```

**Comment by hxiong388** [comment]
@rushilagr I just remembered another thing that may have caused the problem you're seeing. The Google Container Engine cluster needs to have the correct permissions and scope to access any of the other Google Cloud Platform services. Some services, like Stackdriver Logging, have the scope enabled by default. The others, such Stackdriver Error Reporting, need to have the scope enabled during the creation of the cluster.

To do so:
1. Go to the [Google Container Engine page](https://console.cloud.google.com/kubernetes/list) on Cloud Console.
2. Create a new cluster by pressing the `CREATE CLUSTER` button.
3. In the config page, click the `More` link to expand the config options.
4. Within the `Project access` section, select `Enabled` option for the `Cloud Platform`.
5. Make other configuration changes if needed. Click `Create` to finish.

Application running from this newly created cluster should now have proper access to the Stackdriver Error Reporting API.

**Comment by rushilagr** [comment]
Enabling the Cloud Platform access fixed it!
I would suggest the team to make the documentation a bit more clearer.

Thanks !

**Comment by hxiong388** [comment]
I'm glad we find out what the problem is. We'll definitely document this required setting for future GKE users.
