### ISSUE TITLE
VideoIntelligence quickstart crashes on require

### ISSUE THREAD

**Issue by thagomizer** [GoogleCloudPlatform/google-cloud-ruby#1765]
Using the quickstart from the samples, [here](https://github.com/GoogleCloudPlatform/ruby-docs-samples/tree/master/video) with Ruby 2.3.1, 2.4.1, and mac system ruby I get the following error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- grpc/google_rpc_status_utils (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-gax-0.8.11/lib/google/gax/grpc.rb:31:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-gax-0.8.11/lib/google/gax/errors.rb:32:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-gax-0.8.11/lib/google/gax/api_callable.rb:32:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-gax-0.8.11/lib/google/gax.rb:30:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-video_intelligence-0.23.0/lib/google/cloud/video_intelligence/v1beta1/video_intelligence_service_client.rb:28:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ajahammerly/.gem/repos/machine-learning/gems/google-cloud-video_intelligence-0.23.0/lib/google/cloud/video_intelligence/v1beta1.rb:15:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from quickstart.rb:16:in `<main>'
```

**Comment by blowmage** [comment]
@geigerj I thought you yanked the google-gax release that introduced this dependency?

**Comment by blowmage** [comment]
@thagomizer The reason for this is because the google-gax gem is trying to load a file that was introduced in the grpc 1.6.2 gem, but google-gax is not specifying that grpc version on in the dependency. You can solve this by updating your grpc gem to the latest version while we try to get the gem dependencies updated correctly.

**Comment by geigerj** [comment]
Yes, this is my fault. gRPC released a new version (1.6.6) that fixed the issues with this file, and I released a new version of GAX without specifying the right bounds on the dependency. It should be fixed now.

**Comment by geigerj** [comment]
@thagomizer Could you update GAX and close if the issue goes away?

**Comment by thagomizer** [comment]
I'll close the issue once the samples in the docs work.

**Comment by frankyn** [comment]
Question from sample side. All that is required now is `bundle update` and verification of gRPC 1.6.6?

**Comment by geigerj** [comment]
Yes, for this particular issue, that should be it.

**Comment by blowmage** [comment]
@geigerj I see that [google-gax 0.8.12](https://rubygems.org/gems/google-gax/versions/0.8.12) narrows the dependency on grpc, but I think the dependency is now too narrow. A dependency on `~> 1.6.6` means that it won't allow a future 1.7.0 release to be used. I believe the correct dependency to use is `>= 1.6.6, < 2.0`.

**Comment by geigerj** [comment]
@blowmage Sure, we can be looser in the next release. https://github.com/googleapis/gax-ruby/pull/95

**Comment by frankyn** [comment]
@geigerj ruby-docs-samples work with the latest version of the Video Intelligence gem. I have updated the samples in the following PR.

https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/203

**Comment by quartzmo** [comment]
Closing for now since this appears to be resolved. If this is not the case, please re-open.
