### ISSUE TITLE
[Storage] When a bucket-level IAM policy has no assigned users with roles undefined method error is raised.

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-ruby#1965]
Hi all,

When I clear the IAM policy of a bucket using the UI or the Ruby client, I'm unable to view the policy or add new members as I receive the error `NoMethodError: undefined method 'each_with_object' for nil:NilClass`. 

Steps to reproduce:
1. Remove all bucket-level IAM bindings 

```ruby
require "google/cloud/storage"

storage = Google::Cloud::Storage.new

bucket = storage.bucket "bucket-name"

bucket.policy do |policy|
  copy_roles = policy.roles.clone
  copy_roles.each do |role|
     policy.roles[role[0]] = []
  end
end

# NoMethodError: undefined method `each_with_object' for nil:NilClass
```

2. Trying to `puts` the bucket policy continues to error.

```ruby
puts bucket.policy

# NoMethodError: undefined method `each_with_object' for nil:NilClass

```

Gem Version `google-cloud-storage-1.9.0`.

**Comment by blowmage** [comment]
It looks like this might be coming from a Policy protobuf resource that has no bindings because it is now empty.

```ruby
def self.from_gapi gapi
  roles = gapi.bindings.each_with_object({}) do |binding, memo|
    memo[binding.role] = binding.members.to_a
  end
  new gapi.etag, roles
end
```

We should add a guard that checks if bindings is `nil`.

**Comment by blowmage** [comment]
@frankyn Can you post your error's backlog?

**Comment by frankyn** [comment]
@blowmage Apologies for the delay, the backlog is:

```
NoMethodError: undefined method `each_with_object' for nil:NilClass
        from /usr/local/google/home/franknatividad/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/google-cloud-storage-1.9.0/lib/google/cloud/storage/policy.rb:202:in `from_gapi'
        from /usr/local/google/home/franknatividad/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/google-cloud-storage-1.9.0/lib/google/cloud/storage/bucket.rb:1166:in `policy'
        from (irb):5
        from /usr/local/google/home/franknatividad/.rbenv/versions/2.4.3/bin/irb:11:in `<main>'
```

**Comment by frankyn** [comment]
Reviewing PR now.

**Comment by blowmage** [comment]
K, I have been able to reproduce that, and #1966 adds test coverage for it's fix.

**Comment by frankyn** [comment]
Thanks @blowmage!
