### ISSUE TITLE
Support BigQuery Job Regionalization

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#2017]
We need to support BigQuery Regionalization by adding `location` to various Job-related methods and API calls:

* `jobs.get`
  * - [ ] Add `location` optional argument to `Project#job`
* `jobs.cancel`
  * - [ ] Send `location` value to API call made in `Job#cancel`
* `jobs.getQueryResults `
  * - [ ] Send `location` value to API call made by `Job#data`
  * - [ ] Send `location` value to API call made by `Job#wait_until_done!`
* `jobs.insert`
  * - [ ] Add `location` optional argument to `Project#query`, `Project#query_job`, `Dataset#query`, and `Dataset#query_job`
  * - [ ] Add `location` optional argument to `Table#copy`, and `Table#copy_job`
  * - [ ] Add `location` optional argument to `Table#extract`, and `Table#extract_job`
  * - [ ] Add `location` optional argument to `Dataset#load `, `Dataset#load_job`, `Table#load`, and `Table#load_job`
  * - [ ] Add `location` to API call made by `Job#rerun!` (possible optional argument as well?)

**Comment by tswast** [comment]
It might be helpful to reference the Python changes at https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5071. The system test was especially useful in finding gaps in the implementation.

**Comment by quartzmo** [comment]
@tswast Any idea what is causing this error?

```sh
Google::Cloud::Bigquery::bigquery#test_0011_should run a query job with location in a block updater:
Google::Cloud::InvalidArgumentError: invalid: Job could not be run in selected location.
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:401:in `rescue in execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:395:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:280:in `job_query_results'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb:863:in `ensure_schema!'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb:331:in `data'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/acceptance/bigquery/bigquery_test.rb:157:in `block (2 levels) in <top (required)>'
```

```ruby
  it "should run a query job with location in a block updater" do
    region = "EU"
    job = bigquery.query_job publicdata_query do |j|
      j.location = region
    end
    job.must_be_kind_of Google::Cloud::Bigquery::Job
    job.reload!
    job.location.must_equal region
    job.wait_until_done!
    rows = job.data
    rows.total.must_equal 100
  end
```

I'm using project `helical-zone-771`, which is supposed to be whitelisted. Is it something to do with the public dataset?

**Comment by quartzmo** [comment]
Line 157 of the test is: `rows = job.data`

**Comment by tswast** [comment]
@quartzmo Public datasets live in the `US` location. Unfortunately, that means they cannot be queried from the `EU`.

**Comment by tswast** [comment]
In the Python system tests, I loaded a teeny table to query in a non-US region. https://github.com/GoogleCloudPlatform/google-cloud-python/blob/d44dc25bb05f94c71dba0beef32c5303eaa38641/bigquery/tests/system.py#L610-L706

**Comment by quartzmo** [comment]
@tswast Great, thank you! I'll do the same.
