### ISSUE TITLE
QueryJob::Updater incorrectly configures DatasetReference

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-ruby#2027]
When PR #2003 moved [`Service#dataset_ref_from`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/google-cloud-bigquery/v1.1.0/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb#L370-L383) to [`QueryJob::Updater#dataset_ref_from`](https://github.com/tswast/google-cloud-ruby/blob/57309528c475abd94af9cc0ec97e14e000106472/google-cloud-bigquery/lib/google/cloud/bigquery/query_job.rb#L335-L349) it introduced the possibility for the `DatasetReference.project_id` to be incorrectly set to `nil` instead of to the default project, which was the existing behavior. This occurs when only one argument (the dataset) is passed to `QueryJob::Updater#dataset_ref_from`. Because `QueryJob::Updater` does not have the instance variable `@project` (unlike `Service`), the ID of the default project is not set.

Unit test:

```ruby
  it "queries the data with dataset option" do
    mock = Minitest::Mock.new
    bigquery.service.mocked_service = mock

    job_gapi = query_job_gapi(query)
    job_gapi.configuration.query.default_dataset = Google::Apis::BigqueryV2::DatasetReference.new(
      project_id: project,
      dataset_id: "some_random_dataset"
    )
    mock.expect :insert_job, job_gapi, [project, job_gapi]

    job = bigquery.query_job query do |j|
      j.dataset = "some_random_dataset"
    end
    mock.verify

    job.must_be_kind_of Google::Cloud::Bigquery::QueryJob
  end
```

```sh
  1) Error:
Google::Cloud::Bigquery::Project::query_job::updater::mock_bigquery#test_0005_queries the data with dataset option:
MockExpectationError: mocked method :insert_job called with unexpected arguments ["test-project", #<Google::Apis::BigqueryV2::Job:0x00007f92f6dc1820 @configuration=#<Google::Apis::BigqueryV2::JobConfiguration:0x00007f92f6dc1960 @query=#<Google::Apis::BigqueryV2::JobConfigurationQuery:0x00007f92f6dc1aa0 @allow_large_results=nil, @create_disposition=nil, @default_dataset=#<Google::Apis::BigqueryV2::DatasetReference:0x00007f92f6dc11b8 @dataset_id="some_random_dataset", @project_id=nil>, @destination_table=nil, @flatten_results=nil, @maximum_billing_tier=nil, @maximum_bytes_billed=nil, @priority="INTERACTIVE", @query="SELECT name, age, score, active FROM `some_project.some_dataset.users`", @use_legacy_sql=false, @use_query_cache=true, @user_defined_function_resources=[], @write_disposition=nil>>, @job_reference=#<Google::Apis::BigqueryV2::JobReference:0x00007f92f6dc1ca8 @job_id="job_9876543210", @project_id="test-project">>]
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:271:in `block in query_job'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:378:in `block in execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:413:in `block in execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:411:in `loop'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:411:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:378:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/service.rb:270:in `query_job'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/lib/google/cloud/bigquery/project.rb:338:in `query_job'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigquery/test/google/cloud/bigquery/project_query_job_updater_test.rb:125:in `block (2 levels) in <top (required)>'
```

I will fix this and add the missing test coverage.

/cc @blowmage @tswast

**Comment by tswast** [comment]
Thanks for catching.

**Comment by quartzmo** [comment]
@tswast Sure thing, not a problem.
