### ISSUE TITLE
Apply duplication guard on Policy

### ISSUE THREAD

**Issue by blowmage** [GoogleCloudPlatform/google-cloud-ruby#2091]
Apply the same guard against duplicate role members on all the gems that have a IAM Policy class. See #2083.

- [x] Storage
- [ ] Pub/Sub
- [ ] Spanner
- [x] Resource Manager

**Comment by quartzmo** [comment]
Confirming that this was needed for Storage:

```sh
Google::Cloud::InvalidArgumentError: invalid: The member: serviceAccount:xxxx@developer.gserviceaccount.com is listed more than once in the role: roles/storage.objectCreator
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:553:in `rescue in execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:551:in `execute'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/service.rb:200:in `set_bucket_policy'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/bucket.rb:1310:in `update_policy'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/bucket.rb:1273:in `policy'
```

**Comment by quartzmo** [comment]
I could not reproduce the error for Pub/Sub. In Pub/Sub, which uses gRPC, the duplicate was ignored and not added without error.
