### ISSUE TITLE
Couple of acceptance test in Ruby-Storage fail

### ISSUE THREAD

**Issue by suhasm21** [GoogleCloudPlatform/google-cloud-ruby#2339]
URL: https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-storage/acceptance

Steps:
1. git clone https://github.com/GoogleCloudPlatform/google-cloud-ruby
2. cd google-cloud-ruby/google-cloud-storage
3. bundle update
4. bundle exec rake "acceptance[project_id,path_to_json_key_file]"

RESULT:
79 runs, 633 assertions, 0 failures, 2 errors, 2 skips
Finished in 227.637763s, 0.3470 runs/s, 2.7807 assertions/s.

Error 1: Not sure why.
  1) Error:
Google::Cloud::Storage::File::storage#test_0013_should upload and partially download text:
Google::Cloud::Storage::FileVerificationError: The downloaded file failed MD5 verification.
    /home/suhasm/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/file/verifier.rb:34:in `verify_md5!'
    /home/suhasm/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/file.rb:1464:in `verify_file!'
    /home/suhasm/google-cloud-ruby/google-cloud-storage/lib/google/cloud/storage/file.rb:688:in `download'
    /home/suhasm/google-cloud-ruby/google-cloud-storage/acceptance/storage/file_test.rb:365:in `block (3 levels) in <top (required)>'

Error 2: I am guessing this is because the test does not pick the service account key set in the env variable, rather looks for Service account secure-gcp-test-project9@gs-project-accounts.iam.gserviceaccount.com which does not exist. 

It would be great if the test can pick service account set in env variable (this would make the test generic and usable in user owned project)

  2) Error:
Google::Cloud::Storage::Bucket::notification::storage#test_0001_creates a Pub/Sub subscription notification:
Google::Cloud::InvalidArgumentError: 3:Service account secure-gcp-test-project9@gs-project-accounts.iam.gserviceaccount.com does not exist.
    /home/suhasm/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:459:in `rescue in execute'
    /home/suhasm/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:456:in `execute'
    /home/suhasm/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/service.rb:370:in `set_topic_policy'
    /home/suhasm/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb:449:in `update_policy'
    /home/suhasm/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub/topic.rb:415:in `policy'
    /home/suhasm/google-cloud-ruby/google-cloud-storage/acceptance/storage/bucket_notification_test.rb:34:in `block (2 levels) in <top (required)>'

**Comment by dazuma** [comment]
We've seen Error 1 every so often in CI, and we're not sure what's causing it yet. https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/2341 is an attempt to gather more information about it.

Error 2 is indeed a setup/config issue. It works in CI because of how we've set up the environment. You're right—we should set up something so the test can be run elsewhere.

**Comment by quartzmo** [comment]
I believe the solution to Error 2 is to obtain the service account email used in the test from [`Storage::Project#service_account_email`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/project.rb#L88-L91). I will submit a PR that changes the test (and the documentation examples) to use this method to obtain the email.

**Comment by blowmage** [comment]
Have you seen error 1 recently?

**Comment by suhasm21** [comment]
After the fix to Error 2, I re-ran the test and I did not see any issues.
