### ISSUE TITLE
"Key :storage already exists. It will be replaced" warning

### ISSUE THREAD

**Issue by wlipa** [GoogleCloudPlatform/google-cloud-ruby#2350]
I have a rails app that pulls in the storage and error reporting libraries via bundler, like so:

    gem 'google-cloud-storage'
    gem 'google-cloud-error_reporting'

Under ruby 2.5 on Ubuntu 18.04, I consistently get warnings on every app startup:

    Key :storage already exists. It will be replaced. at /home/ops/.gem/ruby/2.5.0/gems/google-cloud-storage-1.13.0/lib/google-cloud-storage.rb:124:in `<top (required)>'
    Key :error_reporting already exists. It will be replaced. at /home/ops/.gem/ruby/2.5.0/gems/google-cloud-error_reporting-0.30.1/lib/google-cloud-error_reporting.rb:134:in `<top (required)>'

After tracing this through a bit, it appears that bundler requires the google-cloud-storage gem first, as expect.  This internally pulls in google/cloud, which then runs auto_load_gems.  This winds up loading google-cloud-storage again (perhaps because the initial require never finished), and we get the duplicate warning.

Is there some way to turn off the auto loading?  I'm not sure why it's being used here, since bundler is managing all gem dependencies.

**Comment by blowmage** [comment]
Hi @wlipa, thanks for opening the issue. I am not sure why this is happening, because when the autoloader attempts to require the file that is requiring the autoloader, a circular require warning should be raised instead of loading the file again and overwriting the configuration.

Since you are using Bundler, could you help us debug this? I have a branch with some changes that I think might address the behavior you are seeing. Can you add the following to your `Gemfile` and let me know if you still see the warnings?

```ruby
gem "google-cloud-core", 
  github: "blowmage/google-cloud-ruby", 
  branch: "autoload-remove-configuration-warning"
```

**Comment by blowmage** [comment]
@wlipa, what version of `google-cloud-core` do you have specified in your Gemfile.lock file?

**Comment by wlipa** [comment]
Happy to test a branch.  Here are the 'goog' lines out of the Gemfile.lock:

      google-api-client (0.23.4)
        googleauth (>= 0.5, < 0.7.0)
      google-cloud-core (1.2.2)
        google-cloud-env (~> 1.0)
      google-cloud-env (1.0.2)
      google-cloud-error_reporting (0.30.1)
        google-cloud-core (~> 1.2)
        google-gax (~> 1.0)
      google-cloud-storage (1.13.0)
        google-api-client (~> 0.23)
        google-cloud-core (~> 1.2)
        googleauth (~> 0.6.2)
      google-gax (1.3.0)
        google-protobuf (~> 3.2)
        googleapis-common-protos (>= 1.3.5, < 2.0)
        googleauth (~> 0.6.2)
      google-protobuf (3.6.1)
      googleapis-common-protos (1.3.7)
        google-protobuf (~> 3.0)
        googleapis-common-protos-types (~> 1.0)
      googleapis-common-protos-types (1.0.2)
        google-protobuf (~> 3.0)
      googleauth (0.6.4)
        google-protobuf (~> 3.1)
        googleapis-common-protos-types (~> 1.0.0)
        google-cloud-core (~> 1.2)
    google-cloud-error_reporting
    google-cloud-storage

**Comment by blowmage** [comment]
@wlipa, what command are you running to generate the errors? I'm not able to reproduce using `rails server`, `rails console`, or `rails test`.

**Comment by wlipa** [comment]
It happens under both `rails server` and `rails console` which is all I've tried.

**Comment by wlipa** [comment]
Same results:

    $ rails c
    Key :storage already exists. It will be replaced. at /home/ops/.gem/ruby/2.5.0/bundler/gems/google-cloud-ruby-86adca585e08/google-cloud-storage/lib/google-cloud-storage.rb:121:in `<top (required)>'
    Key :error_reporting already exists. It will be replaced. at /home/ops/.gem/ruby/2.5.0/bundler/gems/google-cloud-ruby-86adca585e08/google-cloud-error_reporting/lib/google-cloud-error_reporting.rb:134:in `<top (required)>'
    Loading staging environment (Rails 5.1.6)

**Comment by blowmage** [comment]
Are you configuring these gems in your app? If so, are you requiring the gems before you configure them?

**Comment by wlipa** [comment]
No, it's very plain vanilla.  I don't think there is any reference to GCP objects until after the app loads (after the warnings are printed).

**Comment by blowmage** [comment]
> I'm a little confused about the semantics of Kernel.require. If you are requiring a file, and that file causes itself to be required again, is the once-only rule for Kernel.require going to block it? 

Ruby will only load a file once, and will indicate a circular require by raising a warning. My branch you added in your Gemfile protects against that, however. But you are still seeing this behavior, even with my branch. Therefore something else is going on in your app that is causing this.

**Comment by wlipa** [comment]
> Ruby will only load a file once, and will indicate a circular require by raising a warning.

That isn't what I observe, oddly.

a.rb:

    $: << '.'

    puts "a.rb"
    require 'b'
    puts "a.rb over"

b.rb:

    puts "b.rb"
    require 'a'
    puts "b.rb over"

Run:

    $ ruby a.rb 
    a.rb
    b.rb
    a.rb
    a.rb over
    b.rb over
    a.rb over

**Comment by wlipa** [comment]
Never mind that one, the first reference to a.rb wasn't a require.  I'll try to isolate it further.

**Comment by wlipa** [comment]
It looks like the issue is to do with a symbolic link in the bundle path.  I have a .bundle/config like this:

    ---
    BUNDLE_PATH: "/home/ops/apps/myapp/shared/bundle"
    BUNDLE_FROZEN: "true"
    BUNDLE_WITHOUT: "development:test"

where `/home/ops/apps/myapp/shared/bundle` is a symbolic link:

    lrwxrwxrwx 1 ops ops   14 Jul 20 11:29 bundle -> /home/ops/.gem

Changing BUNDLE_PATH to point directly at the target avoids the issue.

**Comment by blowmage** [comment]
Wow, that is wild. I suppose that the autoloader is discovering the files using their real location, and so the same file gets required twice, once with the symlink, and then once again with the real file path.

Can you change your configuration to use a symbolic link again and use my branch? I updated the branch to pass all the comparisons through `File.realpath` and I wonder if that solves the configuration warning while using a symlink.

```ruby
gem "google-cloud-core", 
  github: "blowmage/google-cloud-ruby", 
  branch: "autoload-remove-configuration-warning"
```

**Comment by wlipa** [comment]
The autoload-remove-configuration-warning  branch seems to fix it (no error is shown, but if I comment out the branch gem, it is).

**Comment by blowmage** [comment]
Great news! I will submit those changes to be released then.
