### ISSUE TITLE
Require errors in google-cloud-core 1.2.4 on macOS

### ISSUE THREAD

**Issue by tragiclifestories** [GoogleCloudPlatform/google-cloud-ruby#2423]
OS: 10.12.6
Ruby version: 2.5.1
Bundler version: 1.16.1 & 1.16.4

A routine version bump has caused google-cloud-core to blow up when requiring the various gems, on my machine at least.

```
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'google-cloud-storage'.
Gem Load Error is: No such file or directory @ realpath_rec - /Users/jamesturley/Projects/payments-service/-e
Backtrace for gem load error is:
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/google-cloud-core-1.2.4/lib/google/cloud.rb:193:in `realpath'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/google-cloud-core-1.2.4/lib/google/cloud.rb:193:in `block in auto_load_gems'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/google-cloud-core-1.2.4/lib/google/cloud.rb:192:in `map'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/google-cloud-core-1.2.4/lib/google/cloud.rb:192:in `auto_load_gems'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/google-cloud-core-1.2.4/lib/google/cloud.rb:224:in `<top (required)>'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/google-cloud-storage-1.14.0/lib/google-cloud-storage.rb:22:in `require'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/google-cloud-storage-1.14.0/lib/google-cloud-storage.rb:22:in `<top (required)>'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
/Users/jamesturley/Projects/payments-service/config/application.rb:10:in `<top (required)>'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `require'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:92:in `preload'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/opt/boxen/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
-e:1:in `<main>'
```

It looks to me like this was introduced in #2392. in [`Google::Cloud::auto_load_gems`](https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud.rb#L192-L194) we find

```rb
 previously_loaded_files = Array(caller).map do |backtrace_line|
   File.realpath backtrace_line.split(":").first
 end.uniq
```

logging out the result of `Array(caller)` (line numbers will be off due to the log statement) we get

```rb
["/Users/jamesturley/Projects/payments-service/vendor/bundle/ruby/2.5.0/gems/google-cloud-core-1.2.4/lib/google/cloud.rb:226:in `<top (required)>'",
# ... snip ... 
 "/opt/boxen/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
 "/opt/boxen/rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'",
 "-e:1:in `<main>'"]
```

Which means `"-e"` gets passed to `File.realpath`, which causes a crash.

**Comment by blowmage** [comment]
Thank you for the issue. We will get a new release out that fixes this ASAP. Until then, you can downgrade to google-cloud-core 1.2.3 to avoid the error.

**Comment by tragiclifestories** [comment]
Thanks!

**Comment by blowmage** [comment]
This should be fixed in google-cloud-core 1.2.5. Can you please upgrade and give it a try?

**Comment by tragiclifestories** [comment]
Will do when I get home. Thanks again.
