### ISSUE TITLE
How to delete a directory in bucket

### ISSUE THREAD

**Issue by buithehien1991** [GoogleCloudPlatform/google-cloud-ruby#717]
I'd like to ask about how to delete a exist directory/folder in bucket by gcloud-ruby. 

```
  require "gcloud"

  gcloud = Gcloud.new
  storage = gcloud.storage

  bucket = storage.bucket "my-bucket"
  file = bucket.file "path/to/my-folder"
  file.delete
```

Is right?

Thank you and best regards,
Bui The Hien

**Comment by buithehien1991** [comment]
I tested in rails console with above command but I have error 
```
Gcloud::Storage::ApiError: Not Found
	from /home/hienbt/.rvm/gems/ruby-2.3.0/gems/gcloud-0.10.0/lib/gcloud/storage/bucket.rb:467:in `file'
	from (irb):8
	from /home/hienbt/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /home/hienbt/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/hienbt/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/hienbt/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/hienbt/.rvm/gems/ruby-2.3.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /mnt/DATA/Work/VIENASite/tmp/DeThiMoi2/bin/rails:9:in `require'
	from /mnt/DATA/Work/VIENASite/tmp/DeThiMoi2/bin/rails:9:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

So, could you please help me how to delete a folder/directory in Cloud Storage. 
Thank you so much.

**Comment by blowmage** [comment]
Hi @buithehein1991, to delete a file you will need to specify the exact file name. See [`File#delete`](https://googlecloudplatform.github.io/gcloud-ruby/#/docs/v0.10.0/gcloud/storage/file?method=delete-instance)

```ruby
require "gcloud"

gcloud = Gcloud.new
storage = gcloud.storage

bucket = storage.bucket "my-bucket"

file = bucket.file "path/to/my-file.ext"
file.delete
```

If you want to delete all files that match a directory, you will first have to select the files, and then delete them. 

```ruby
require "gcloud"

gcloud = Gcloud.new
storage = gcloud.storage

bucket = storage.bucket "my-bucket"

files = bucket.files prefix: "path/to/my-folder"
files.map &:delete
```

This is because there are no directories in Google Cloud Storage, only files. Using `prefix` and `delimiter` we can query the files as if there were directories.

**Comment by blowmage** [comment]
@buithehien1991 Does this answer your question? If so, can this issue be closed?
