### ISSUE TITLE
Cannot query entities with embedded entities

### ISSUE THREAD

**Issue by Dragor2** [GoogleCloudPlatform/google-cloud-ruby#857]
I ran into this problem while messing around with datastores to get an idea of how to use them, but ran into the following error: 

> /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/key.rb:264:in `dup': can't dup NilClass (TypeError)

I created a small ruby script to reproduce the issue. Follow these steps to reproduce:

1.  Create 2 Entities in a cloud datastore via the Google Console. One that has an Embedded Entity, other that doesn't have one.
2. Run the following script (adjust according to your datastore details)
```
require "gcloud"

gcloud = Gcloud.new "[my-project-id]", "[my-serviceaccount.json]"
datastore = gcloud.datastore

puts "Querying Entity without Embedded Entities..."
query = datastore.query("EntityWithoutEmbeddedEntity").limit(5)
result = datastore.run query

puts "Results:"
puts result 

puts "Querying Entity with Embedded Entities..."
query = datastore.query("EntityWithEmbeddedEntity").limit(5)
result = datastore.run query

puts "Results:"
puts result 
```

My output:
```
root@9fefd6b37da3:/myapp# ruby test.rb 
I0826 06:38:20.748835468       5 ev_epoll_linux.c:84]        epoll engine will be using signal: 36
D0826 06:38:20.749478619       5 ev_posix.c:106]             Using polling engine: epoll
Querying Entity without Embedded Entities...
Results:
#<Gcloud::Datastore::Entity:0x0056114d360ba0>
Querying Entity with Embedded Entities...
/usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/key.rb:264:in `dup': can't dup NilClass (TypeError)
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/key.rb:264:in `from_grpc'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/entity.rb:376:in `from_grpc'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/grpc_utils.rb:59:in `from_value'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/properties.rb:82:in `block in from_grpc'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/properties.rb:82:in `each'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/properties.rb:82:in `map'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/properties.rb:82:in `from_grpc'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/entity.rb:377:in `from_grpc'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/dataset/query_results.rb:360:in `block in from_grpc'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/dataset/query_results.rb:359:in `map'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/dataset/query_results.rb:359:in `from_grpc'
        from /usr/local/bundle/gems/gcloud-0.12.2/lib/gcloud/datastore/dataset.rb:394:in `run'
        from test.rb:17:in `<main>'
root@9fefd6b37da3:/myapp# 
```

I use the docker container for Ruby 2.3 with gcloud gem 0.12.2.

**Comment by blowmage** [comment]
Thanks for reporting the issue!
